### ISSUE TITLE
Can't install package from Chocolatey

### ISSUE THREAD

**Issue by jp311** [OneGet/chocolateyprototype#2]
`PS> Install-Package ConEmu`
...
`PS> Get-Package ConEmu`

```
Name                           Version          Source           Summary
----                           -------          ------           -------
ConEmu                         15.7.28.0        C:\Chocolatey... ConEmu-Maximu...
```

But ConEmu is not installed.

**Comment by scriptdaemon** [comment]
So far this is true for me as well with all packages I've tried to install: autohotkey, consolez, and cyg-get (and, via dependency, cygwin). It'll add a folder in C:/Chocolatey for each, but I can't find the *.exe files anywhere nor are they added to the path env var, etc.

**Comment by xumins** [comment]
Hi Kenneth,
The chocolatey provider we have in GitHub OneGet project is only a prototype that Garrett implemented 1 year ago. We do not have plan to enhance it from Microsoft side, and we expect the community to take the ownership to improve it further. Hope this explains the situation.

Thanks,
Xumin

**Comment by CMCDragonkai** [comment]
You need to change your execution policy.

```
Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
```

Then things like VLC installs for me.

But when I tried installing chocolatey using this chocolatey provider, it didn't create any binaries into the PATH anywhere, and I couldn't run `choco`. But I do see the `choco` binary at `C:\Chocolatey`.
