### ISSUE TITLE
Can't uninstall the provider

### ISSUE THREAD

**Issue by phw** [OneGet/chocolateyprototype#3]
After running `get-packageprovider -name chocolatey` I ended up having a chocolatey provider, which seems to be non funtional due to #2 .

```
PS C:\WINDOWS\system32> Get-PackageProvider

Name                     Version          DynamicOptions
----                     -------          --------------
msu                      10.0.10240.16384 {}
msi                      10.0.10240.16384 {AdditionalArguments}
Programs                 10.0.10240.16384 {IncludeWindowsInstaller, IncludeSystemComponent}
Chocolatey               2.8.5.130        {SkipDependencies, ContinueOnFailure, ExcludeVersion, ForceX86...}
NuGet                    2.8.5.127        {Destination, SkipDependencies, ContinueOnFailure, ExcludeVersion...}
PSModule                 1.0.0.0          {PackageManagementProvider, Location, InstallUpdate, InstallationPolicy...}
```

Fine so far, but I have not yet found a way to completely remove the provider again. On https://github.com/OneGet/oneget/wiki/cmdlets I see only `Unregister-PackageSource`, but no way to remove the provider itself. Can this be done manually?

**Comment by xumins** [comment]
Hi Philipp,
For removing the provider, you can directly remove it from the following folders that contains the provider binaries:
·         If the user is running Windows PowerShell with elevated rights: $env:PROGRAMFILES\PackageManagement\ProviderAssemblies
·         If the user is not running with elevated rights: $env:LOCALAPPDATA\PackageManagement\ProviderAssemblies
Hope this helps.
Xumin

**Comment by phw** [comment]
Thanks a lot for the help, that worked :)
